module.exports = {
  ...require('./actions.json'),
  ...require('./api.json'),
  ...require('./forms.json'),
  ...require('./getters.json'),
  ...require('./guide.json'),
  ...require('./hot-reload.json'),
  ...require('./installation.json'),
  ...require('./introduction.json'),
  ...require('./modules.json'),
  ...require('./mutations.json'),
  ...require('./plugins.json'),
  ...require('./state.json'),
  ...require('./strict.json'),
  ...require('./structure.json'),
  ...require('./testing.json'),
};
