module.exports = [
  "Ajax Bar",
  "Avatar",
  "Badge",
  "Banner",
  "Bar",
  "Breadcrumbs",
  // Begin "Buttons",
  "Button",
  "Button Group",
  "Button Dropdown",
  // End "Buttons",
  "Card",
  "Carousel",
  // "Chat Message",
  "Chat",
  "Chip",
  "Circular Progress",
  "Color Picker",
  "Dialog",
  // " - WYSIWYG" removed
  "Editor",
  "Expansion Item",
  // Begin "Form Components",
  // "Input Textfield",
  "Input",
  "Select",
  "File picker",
  "Form",
  // "Field (wrapper)",
  "Field",
  "Radio",
  "Checkbox",
  "Toggle",
  "Button Toggle",
  "Option Group",
  "Slider",
  "Range",
  "Time",
  //"Time Picker",
  // "Date Picker",
  "Date",
  // End "Form Components",
  "Icon",
  "Img",
  "Infinite Scroll",
  "Inner Loading",
  "Intersection",
  "Knob",
  "Linear Progress",
  "List & List Items",
  "Markup Table",
  "Menu",
  "No SSR",
  // Begin "Observers",
  // " (for Element)" removed
  "Resize Observer",
  "Scroll Observer",
  // End "Observers",
  "Pagination",
  "Parallax",
  "Popup Edit",
  "Popup Proxy",
  "Pull to refresh",
  "Rating",
  "Responsive",
  "Scroll Area",
  "Separator",
  "Skeleton",
  "Slide Item",
  "Slide Transition",
  "Space",
  "Spinners",
  "Splitter",
  "Stepper",
  "Table",
  "Tabs",
  "Tab Panels",
  "Timeline",
  "Toolbar",
  "Tooltip",
  "Tree",
  "Uploader",
  "Video",
  "Virtual Scroll"
];
